# Site settings
title: "조상호 | 주니어 프로그래머"
description: ""

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "조상호"
resume_title:                   ""

# used for the contact button in _layouts/resume.html
resume_contact_email:           "sangho3725@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     "sangho3725@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p></p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
#resume_section_experience:      true
resume_section_education:       true  #학력
resume_section_projects:        true  #프로젝트
resume_section_skills:          true  #스킬
resume_section_recognition:     true 
#resume_section_links:           true  
resume_section_associations:    false
resume_section_certificated:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://cydnus.github.io/portfolio"
  resume_email_url:           "sangho3725@gmail.com"
  #resume_twitter_url:           ""
  #resume_dribbble_url:          ""
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          """
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           ""
  #resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
#theme: resume
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
